name: Build and Deployment

on:
  push:
    branches: [main]

  workflow_dispatch:

env:
  ENV: PROD
  APP: 'Read Your Bible Through Server'

jobs:
  start-notify:
    name: Notify of Build Start
    runs-on: ubuntu-latest
    env:
      ENV: PROD
      NOTIFY_INCOMING_WEBHOOK: ${{ secrets.NOTIFY_INCOMING_WEBHOOK }}

    steps:
      - uses: tferreira/matterfy@releases/v1
        if: always()
        with:
          type: 'cancel'
          job_name: '*[${{ env.APP }}]* Starting Build and Deployment to *${{ env.ENV }}*...'
          url: ${{ env.NOTIFY_INCOMING_WEBHOOK }}

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ secrets.APP_NAME }}
      NOTIFY_INCOMING_WEBHOOK: ${{ secrets.NOTIFY_INCOMING_WEBHOOK }}

      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_REGISTRY_LOGIN_SERVER: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
      AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      AZURE_REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

    steps:
      - name: Check out code
        id: checkout
        uses: actions/checkout@v5

      - name: Read node from package.json
        uses: culshaw/read-package-node-version-actions@v1
        id: read-package-json

      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Log into Azure docker
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ env.AZURE_REGISTRY_USERNAME }}
          password: ${{ env.AZURE_REGISTRY_PASSWORD }}

      - name: Build, tag, and push image to Azure
        env:
          REGISTRY: ${{ env.AZURE_REGISTRY_LOGIN_SERVER }}
          REPOSITORY: ${{ env.APP_NAME }}
          IMAGE_TAG: ${{ steps.read-package-json.outputs.version }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:latest -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:${{ github.sha }} .
          docker push $REGISTRY/$REPOSITORY:latest
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:${{ github.sha }}

      - name: Notify of failed build
        uses: tferreira/matterfy@releases/v1
        if: ${{ failure() }}
        with:
          type: ${{ job.status }}
          job_name: '*[${{ env.APP }}]* Failed to Build for *${{ env.ENV }}*'
          url: ${{ env.NOTIFY_INCOMING_WEBHOOK }}

  deploy:
    needs: [build]
    name: Deploy
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ secrets.APP_NAME }}
      NOTIFY_INCOMING_WEBHOOK: ${{ secrets.NOTIFY_INCOMING_WEBHOOK }}

      AZURE_CREDENTIALS: ${{ secrets.AZURE_SERVICE_APP_CREDENTIALS }}
      AZURE_REGISTRY_LOGIN_SERVER: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

    steps:
      - name: Azure deployment
        uses: azure/webapps-deploy@v3.0.6
        with:
          publish-profile: ${{ env.AZURE_CREDENTIALS }}
          app-name: ${{ env.APP_NAME }}
          images: ${{ env.AZURE_REGISTRY_LOGIN_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }}
          resource-group-name: ${{ env.AZURE_RESOURCE_GROUP }}

      - name: Notify of failed deploy
        uses: tferreira/matterfy@releases/v1
        if: ${{ failure() }}
        with:
          type: ${{ job.status }}
          job_name: '*[${{ env.APP }}]* Failed to Deploy to *${{ env.ENV }}*'
          url: ${{ env.NOTIFY_INCOMING_WEBHOOK }}

  end-notify:
    needs: [build, deploy]
    name: Notify of Deploy Complete
    runs-on: ubuntu-latest
    env:
      NOTIFY_INCOMING_WEBHOOK: ${{ secrets.NOTIFY_INCOMING_WEBHOOK }}

    steps:
      - uses: tferreira/matterfy@releases/v1
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*[${{ env.APP }}]* Successfully Completed Build and Deployment to *${{ env.ENV }}*'
          url: ${{ env.NOTIFY_INCOMING_WEBHOOK }}
